# Generated by Django 5.2.8 on 2026-01-19 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment', verbose_name='備品'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='承認有無'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下'), ('returned', '返却済み')], default='pending', max_length=20, verbose_name='申請状況'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申請者'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.TextField(verbose_name='現在の状態'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='機器の詳細説明'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_pics/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='備品名'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial',
            field=models.CharField(max_length=50, unique=True, verbose_name='管理番号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', '利用可能'), ('borrowed', '貸出中'), ('damaged', '故障中')], default='available', max_length=20, verbose_name='在庫状況'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('student', '学生')], default='student', max_length=10, verbose_name='利用区分'),
        ),
    ]
